version: "3.8"

services:
  app:
    container_name: dev-front
    image: dev-front
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/:/app/
    ports:
      - "3000:3000"
